# Generated by Django 6.0.3 on 2026-04-23 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def migrate_announcement_state(apps, schema_editor):
    Announcement = apps.get_model("communications", "Announcement")
    for announcement in Announcement.objects.all():
        if announcement.scope == "major":
            announcement.scope = "global"
        announcement.status = "published" if announcement.is_published else "draft"
        announcement.publish_date = announcement.created_at
        announcement.save(update_fields=["scope", "status", "publish_date"])


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0002_admin_interface_updates"),
        ("communications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="announcement",
            old_name="posted_by",
            new_name="created_by",
        ),
        migrations.AddField(
            model_name="announcement",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="announcements/"),
        ),
        migrations.AddField(
            model_name="announcement",
            name="expiry_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="announcement",
            name="priority",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="announcement",
            name="publish_date",
            field=models.DateTimeField(default=timezone.now),
        ),
        migrations.AddField(
            model_name="announcement",
            name="send_notification",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="announcement",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="target_audience",
            field=models.ManyToManyField(
                blank=True,
                related_name="announcements",
                to="assignments.studygroup",
            ),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("all", "All"),
                    ("professors", "Professors"),
                    ("students", "Students"),
                    ("admins", "Admins"),
                ],
                default="all",
                max_length=20,
            ),
        ),
        migrations.RunPython(migrate_announcement_state, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="announcement",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="announcement",
            name="major",
        ),
        migrations.AlterField(
            model_name="announcement",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="announcements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="scope",
            field=models.CharField(
                choices=[
                    ("global", "Global"),
                    ("course", "Course"),
                    ("group", "Group"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
