# Generated by Django 6.0.3 on 2026-04-23 18:10

from django.db import migrations, models


def normalize_enrollment_statuses(apps, schema_editor):
    Enrollment = apps.get_model("courses", "Enrollment")
    Enrollment.objects.filter(status__in=["completed", "blocked"]).update(status="inactive")
    Enrollment.objects.filter(status="dropped").update(status="withdrawn")


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="material",
            field=models.FileField(
                blank=True, null=True, upload_to="courses/materials/"
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.RunPython(normalize_enrollment_statuses, migrations.RunPython.noop),
    ]
