# Generated by Django 6.0.3 on 2026-04-23 18:00

from django.db import migrations, models


def copy_study_group_members(apps, schema_editor):
    quote_name = schema_editor.quote_name
    cursor = schema_editor.connection.cursor()
    cursor.execute(
        f"""
        INSERT INTO {quote_name('assignments_studygroup_members')}
            ({quote_name('studygroup_id')}, {quote_name('studentprofile_id')})
        SELECT {quote_name('group_id')}, {quote_name('student_id')}
        FROM {quote_name('assignments_studygroupmember')}
        """
    )


def normalize_submission_statuses(apps, schema_editor):
    Submission = apps.get_model("assignments", "Submission")
    Submission.objects.filter(status__in=["submitted", "late"]).update(status="pending")


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="assignments/attachments/"
            ),
        ),
        migrations.AddField(
            model_name="studygroup",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="study_groups",
                to="accounts.studentprofile",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("graded", "Graded"),
                    ("returned", "Returned"),
                    ("error", "Error"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.RunPython(copy_study_group_members, migrations.RunPython.noop),
        migrations.RunPython(normalize_submission_statuses, migrations.RunPython.noop),
        migrations.DeleteModel(
            name="StudyGroupMember",
        ),
    ]
