from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView

from .views import (
    auth_login,
    auth_logout,
    auth_me,
    auth_register_student,
    professor_announcement_detail,
    professor_announcements,
    professor_assignment_submissions,
    professor_assignments,
    professor_course_detail,
    professor_courses,
    professor_dashboard,
    professor_grade_submission,
    professor_stats,
    professor_upload_material,
    public_majors,
    public_stats,
    student_announcements,
    student_assignments,
    student_course_detail,
    student_courses,
    student_dashboard,
    student_grades,
    student_submit_assignment,
)


urlpatterns = [
    path("auth/login/", auth_login, name="auth_login"),
    path("auth/register/student/", auth_register_student, name="auth_register_student"),
    path("auth/logout/", auth_logout, name="auth_logout"),
    path("auth/refresh/", TokenRefreshView.as_view(), name="auth_refresh"),
    path("auth/me/", auth_me, name="auth_me"),
    path("student/dashboard/", student_dashboard, name="student_dashboard"),
    path("student/courses/", student_courses, name="student_courses"),
    path("student/courses/<uuid:course_id>/", student_course_detail, name="student_course_detail"),
    path("student/assignments/", student_assignments, name="student_assignments"),
    path("student/assignments/<uuid:assignment_id>/submit/", student_submit_assignment, name="student_submit_assignment"),
    path("student/grades/", student_grades, name="student_grades"),
    path("student/announcements/", student_announcements, name="student_announcements"),
    path("professor/dashboard/", professor_dashboard, name="professor_dashboard"),
    path("professor/courses/", professor_courses, name="professor_courses"),
    path("professor/courses/<uuid:course_id>/", professor_course_detail, name="professor_course_detail"),
    path("professor/courses/<uuid:course_id>/materials/", professor_upload_material, name="professor_upload_material"),
    path("professor/assignments/", professor_assignments, name="professor_assignments"),
    path("professor/assignments/<uuid:assignment_id>/submissions/", professor_assignment_submissions, name="professor_assignment_submissions"),
    path("professor/submissions/<uuid:submission_id>/grade/", professor_grade_submission, name="professor_grade_submission"),
    path("professor/stats/", professor_stats, name="professor_stats"),
    path("professor/announcements/", professor_announcements, name="professor_announcements"),
    path("professor/announcements/<uuid:announcement_id>/", professor_announcement_detail, name="professor_announcement_detail"),
    path("public/majors/", public_majors, name="public_majors"),
    path("public/stats/", public_stats, name="public_stats"),
]
